name: task_app
description: "This app was build to help manage your daily activity. It is smooth and very effective. Enjoy it and make the best of your day"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1
versionName: 'Task App'


environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3+1
  path_provider: ^2.1.3
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.0
  path: ^1.9.0
  shared_preferences: ^2.2.3
  table_calendar: ^3.1.1


  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  package_info_plus: ^8.0.0
  permission_handler: ^11.3.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.2.16

  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/taskapp.png

  

flutter_native_splash:
  color: "#ffffff"  # Set your desired background color
  image: assets/taskapp.png
  android: true
  ios: true


  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
